name: Build Unsigned iOS App

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Force HTTPS in Podfile
      run: |
        cd ios
        # This command forcefully searches the Podfile and overwrites the private SSH link with a public HTTPS link
        sed -i '' 's/git@github.com:/https:\/\/github.com\//g' Podfile

    - name: Install iOS Pods (Dependencies)
      run: |
        cd ios
        pod install

    - name: Build the iOS app (Unsigned)
      run: |
        cd ios
        xcodebuild clean build \
          -workspace "EdUSpace.xcworkspace" \
          -scheme "EdUSpace" \
          -sdk iphoneos \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Package the .ipa file
      run: |
        APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" | head -n 1)
        echo "Found app at $APP_PATH"
        
        mkdir Payload
        cp -r "$APP_PATH" Payload/
        zip -qr app.ipa Payload

    - name: Upload .ipa so you can download it
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-ios-app
        path: app.ipa
